# Generated by Django 6.0.5 on 2026-05-15 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(max_length=100, verbose_name='Nombre del Local')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('encargado', models.CharField(max_length=100, verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
                'ordering': ['nombre_local'],
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='Patente')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MANTENCION', 'En Mantención')], default='DISPONIBLE', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Asignación')),
                ('es_reemplazo', models.BooleanField(default=False, verbose_name='¿Es reemplazo?')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='app_movimientos.farmacia', verbose_name='Farmacia')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='app_movimientos.moto', verbose_name='Moto')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='app_movimientos.motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turno',
                'unique_together': {('motorista', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Registro')),
                ('direccion_destino', models.CharField(max_length=255, verbose_name='Dirección de Destino')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20, verbose_name='Estado del Despacho')),
                ('tipo_movimiento', models.CharField(choices=[('DIRECTO', 'Directo'), ('RECETA', 'Con Receta'), ('TRASLADO', 'Traslado entre locales'), ('REENVIO', 'Reenvío')], default='DIRECTO', max_length=20, verbose_name='Tipo de Movimiento')),
                ('asignacion_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='app_movimientos.asignacionturno', verbose_name='Turno Asignado')),
            ],
            options={
                'verbose_name': 'Movimiento de Despacho',
                'verbose_name_plural': 'Movimientos de Despacho',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
