# Generated by Django 6.0.5 on 2026-05-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('rol', models.CharField(choices=[('ADMIN', 'Admin'), ('MOTORISTA', 'Motorista'), ('GENERICO', 'Usuario generico')], default='GENERICO', max_length=20, verbose_name='Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
