# Generated by Django 6.0.5 on 2026-06-08 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movimientos', '0002_usuariosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='region',
            field=models.CharField(choices=[('ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('TARAPACA', 'Región de Tarapacá'), ('ANTOFAGASTA', 'Región de Antofagasta'), ('ATACAMA', 'Región de Atacama'), ('COQUIMBO', 'Región de Coquimbo'), ('VALPARAISO', 'Región de Valparaíso'), ('METROPOLITANA', 'Región Metropolitana de Santiago'), ('OHIGGINS', "Región del Libertador General Bernardo O'Higgins"), ('MAULE', 'Región del Maule'), ('NUBLE', 'Región de Ñuble'), ('BIOBIO', 'Región del Biobío'), ('ARAUCANIA', 'Región de La Araucanía'), ('LOS_RIOS', 'Región de Los Ríos'), ('LOS_LAGOS', 'Región de Los Lagos'), ('AYSEN', 'Región de Aysén del General Carlos Ibáñez del Campo'), ('MAGALLANES', 'Región de Magallanes y de la Antártica Chilena')], max_length=20, null=True, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motoristas', to='app_movimientos.farmacia', verbose_name='Farmacia asignada'),
        ),
    ]
