# Generated by Django 6.0.5 on 2026-06-08 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def validar_pedidos_entregados(apps, schema_editor):
    Movimiento = apps.get_model('app_movimientos', 'Movimiento')
    Movimiento.objects.filter(estado='ENTREGADO').update(
        validado=True,
        fecha_validacion=models.F('fecha_hora'),
    )


def revertir_validacion_inicial(apps, schema_editor):
    Movimiento = apps.get_model('app_movimientos', 'Movimiento')
    Movimiento.objects.filter(validado_por__isnull=True).update(
        validado=False,
        fecha_validacion=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app_movimientos', '0004_alter_farmacia_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='validado',
            field=models.BooleanField(default=False, verbose_name='Pedido validado'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.RunPython(validar_pedidos_entregados, revertir_validacion_inicial),
    ]
