# Generated by Django 6.0.5 on 2026-06-08 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movimientos', '0005_movimiento_fecha_validacion_movimiento_validado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_anulados', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='motivo_anulacion',
            field=models.TextField(blank=True, verbose_name='Motivo de anulación'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Fallido'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Despacho'),
        ),
    ]
