# Generated by Django 6.0.5 on 2026-06-11 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movimientos', '0015_movimiento_farmacia_destino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('turno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno Habitual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operadora', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema')),
            ],
            options={
                'verbose_name': 'Operadora',
                'verbose_name_plural': 'Operadoras',
            },
        ),
    ]
